# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x1a\x1bgoogle/protobuf/empty.proto\"c\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x17\n\x0fpublishing_year\x18\x03 \x01(\x05\x12\x15\n\x05genre\x18\x02 \x01(\x0e\x32\x06.Genre\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12\x0c\n\x04isbn\x18\x04 \x01(\x05\"\x1f\n\x0f\x42ookRequestIsbn\x12\x0c\n\x04isbn\x18\x01 \x01(\x05\"I\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x01(\x05\x12\x16\n\x05\x62ook1\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x42\x06\n\x04\x62ook*8\n\x05Genre\x12\x13\n\x0fSCIENCE_FICTION\x10\x00\x12\x0b\n\x07\x46\x41NTASY\x10\x01\x12\r\n\tSELF_HELP\x10\x02*\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x32g\n\x10InventoryService\x12-\n\nCreateBook\x12\x05.Book\x1a\x16.google.protobuf.Empty\"\x00\x12$\n\x07GetBook\x12\x10.BookRequestIsbn\x1a\x05.Book\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=255
  _GENRE._serialized_end=311
  _STATUS._serialized_start=313
  _STATUS._serialized_end=347
  _BOOK._serialized_start=46
  _BOOK._serialized_end=145
  _BOOKREQUESTISBN._serialized_start=147
  _BOOKREQUESTISBN._serialized_end=178
  _INVENTORYITEM._serialized_start=180
  _INVENTORYITEM._serialized_end=253
  _INVENTORYSERVICE._serialized_start=349
  _INVENTORYSERVICE._serialized_end=452
# @@protoc_insertion_point(module_scope)
